#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook "apt"
cookbook "apache2"
cookbook "postgresql"
cookbook "nano"
cookbook "git"
cookbook "screen"
cookbook "build-essential"
cookbook "openssl"